VERILOG = ../src/vic20.v ../src/cpu.v ../src/ALU.v \
	  ../src/keyboard.v ../src/ps2.v ../src/dpram.v \
	  ../src/m6522.v ../src/video.v ../src/hdmi.v pll.v ../src/audio.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v \
	  ../src/osd/spi_ram_btn.v ../src/osd/spirw_slave_v.v \

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

